# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main CI - Backend

on:
  pull_request:
    branches:
      - 'dev'

jobs:
  Backend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install --saveDev

      - name: Running production build
        run: npm run build

      - name: Running tests
        run: npm run test:force

      - name: Running lint
        run: npm run lint:check
